package jp.co.translacat.languagelearning.features.leveltest.domain.model

import kotlinx.serialization.Serializable

@Serializable
internal enum class LevelTestItemType {
    VOCAB_CONTEXT_CHOICE,
    VOCAB_PARAPHRASE_CHOICE,
    GRAMMAR_FORM_CHOICE,
    GRAMMAR_SENTENCE_ORDER,
    READING_GIST,
    READING_DETAIL,
    READING_DISCOURSE_FUNCTION,
    READING_TEXT_INFERENCE,
    LISTENING_GIST_CHOICE,
    LISTENING_DETAIL_CHOICE,
    LISTENING_DICTATION,
    LISTENING_INTERPRETATION,
    WRITING_TRANSLATION,
    WRITING_GUIDED_SENTENCE,
    WRITING_SCENARIO_RESPONSE,
    WRITING_SHORT_PARAGRAPH,
    SPEAKING_REPEAT,
    SPEAKING_GUIDED_RESPONSE,
    SPEAKING_SHORT_RESPONSE
}
