-- Writing의 신규 LL 데이터만 수용한다. 기존 Core ID/행을 복사하거나 재해석하지 않는다.
-- 사용자 참조는 LL learner로 한정하고, 하위 행은 복합 FK로 소유자를 고정한다.

CREATE TABLE language_learning_daily_set (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    learning_date DATE NOT NULL,
    writing_type VARCHAR(30) NOT NULL,
    snapshot_id VARCHAR(100) NOT NULL,
    sentence_count INT NOT NULL,
    status VARCHAR(30) NOT NULL,
    snapshot_json TEXT NOT NULL,
    prompt_version VARCHAR(100) NULL,
    regeneration_count INT NOT NULL DEFAULT 0,
    completed_at DATETIME(6) NULL,
    failure_message VARCHAR(1000) NULL,
    generation_token VARCHAR(36) NULL,
    generation_lease_until DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_ll_w_set_user_date_type UNIQUE (user_id, learning_date, writing_type),
    CONSTRAINT uk_ll_w_set_snapshot UNIQUE (snapshot_id),
    CONSTRAINT uk_ll_w_set_id_user UNIQUE (id, user_id),
    CONSTRAINT fk_ll_w_set_learner FOREIGN KEY (user_id) REFERENCES language_learning_learner (user_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_ll_w_set_type CHECK (writing_type IN ('TRANSLATION', 'GUIDED', 'FREE')),
    CONSTRAINT ck_ll_w_set_status CHECK (status IN ('GENERATING', 'PARTIAL', 'READY', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_ll_w_set_sentence_count CHECK (sentence_count > 0),
    CONSTRAINT ck_ll_w_set_regeneration_count CHECK (regeneration_count >= 0),
    INDEX idx_ll_w_set_generation (status, generation_lease_until, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE language_learning_daily_item (
    id BIGINT NOT NULL AUTO_INCREMENT,
    daily_set_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    item_order INT NOT NULL,
    difficulty VARCHAR(30) NOT NULL,
    origin_text TEXT NOT NULL,
    keywords_json TEXT NOT NULL,
    focus_metrics_json TEXT NOT NULL,
    focus_reason TEXT NOT NULL,
    provided_facts_json TEXT NULL,
    required_intents_json TEXT NULL,
    response_constraints_json TEXT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_ll_w_item_set_order UNIQUE (daily_set_id, item_order),
    CONSTRAINT uk_ll_w_item_id_user UNIQUE (id, user_id),
    CONSTRAINT fk_ll_w_item_set_owner FOREIGN KEY (daily_set_id, user_id) REFERENCES language_learning_daily_set (id, user_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_ll_w_item_order CHECK (item_order > 0),
    CONSTRAINT ck_ll_w_item_difficulty CHECK (difficulty IN ('REVIEW', 'NORMAL', 'CHALLENGE')),
    INDEX idx_ll_w_item_set (daily_set_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE language_learning_writing_answer (
    id BIGINT NOT NULL AUTO_INCREMENT,
    daily_item_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    attempt_date DATE NOT NULL,
    answer_text TEXT NOT NULL,
    submitted_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_ll_w_answer_item_date UNIQUE (daily_item_id, attempt_date),
    CONSTRAINT uk_ll_w_answer_id_user UNIQUE (id, user_id),
    CONSTRAINT fk_ll_w_answer_item_owner FOREIGN KEY (daily_item_id, user_id) REFERENCES language_learning_daily_item (id, user_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    INDEX idx_ll_w_answer_user (user_id, submitted_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE language_learning_writing_evaluation (
    id BIGINT NOT NULL AUTO_INCREMENT,
    answer_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    evaluation_context VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    overall_score INT NULL,
    meaning_score INT NULL,
    grammar_score INT NULL,
    vocabulary_score INT NULL,
    naturalness_score INT NULL,
    expression_score INT NULL,
    strengths_json TEXT NULL,
    weaknesses_json TEXT NULL,
    corrections_json TEXT NULL,
    recommended_answers_json TEXT NULL,
    explanation_json TEXT NULL,
    profile_signals_json TEXT NULL,
    evaluation_rubric_version VARCHAR(100) NULL,
    scoring_policy_version VARCHAR(100) NULL,
    prompt_version VARCHAR(100) NULL,
    evaluated_at DATETIME(6) NULL,
    failure_message VARCHAR(1000) NULL,
    evaluation_token VARCHAR(36) NULL,
    evaluation_lease_until DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_ll_w_eval_answer UNIQUE (answer_id),
    CONSTRAINT fk_ll_w_eval_answer_owner FOREIGN KEY (answer_id, user_id) REFERENCES language_learning_writing_answer (id, user_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_ll_w_eval_context CHECK (evaluation_context = 'DAILY'),
    CONSTRAINT ck_ll_w_eval_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED')),
    INDEX idx_ll_w_eval_recovery (status, evaluation_lease_until, id),
    INDEX idx_ll_w_eval_user (user_id, evaluated_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
